/* CVS $Id: $ */
package org.qualipso.advdoc.coreapi.ontology; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from ontologyqualipso_versioncontrol.owl 
 * @author Auto-generated by schemagen on 11 abr 2008 14:28 
 */
public class QualiPSoVC {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The user who created the revision.</p> */
    public static final ObjectProperty author = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#author" );
    
    /** <p>A version of a file.</p> */
    public static final ObjectProperty hasFile = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#hasFile" );
    
    /** <p>A version of a file.</p> */
    public static final ObjectProperty hasRevision = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#hasRevision" );
    
    /** <p>The repository that contains this versioned file.</p> */
    public static final ObjectProperty hasRepository = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#hasRepository" );
    
    /** <p>Lines added or removed to the file in the revision.</p> */
    public static final DatatypeProperty state = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#state" );
    
    /** <p>The date of creation of the revision.</p> */
    public static final DatatypeProperty date = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#date" );
    
    /** <p>The message or notes of this revision.</p> */
    public static final DatatypeProperty commitMessage = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#commitMessage" );
    
    /** <p>The name of the branch in which this revision is included.</p> */
    public static final DatatypeProperty branch = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#branch" );
    
    /** <p>The number of the revision.</p> */
    public static final DatatypeProperty number = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#number" );
    
    /** <p>The full path of the file. It contains all the folder names starting at version 
     *  control module.</p>
     */
    public static final DatatypeProperty fullPath = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#fullPath" );
    
    /** <p>A version of a file.</p> */
    public static final OntClass Revision = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#Revision" );
    
    /** <p>A versioned file from the file system.</p> */
    public static final OntClass File = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_versioncontrol#File" );
    
}
