/* CVS $Id: $ */
package org.qualipso.advdoc.coreapi.ontology; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from ontologyqualipso_source_code.owl 
 * @author Auto-generated by schemagen on 11 abr 2008 14:28 
 */
public class QualiPSoSC {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.qualipso.org/ontology/doc/qualipso_source_code#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty extendsInterface = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#extendsInterface" );
    
    public static final ObjectProperty hasReturnValue = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasReturnValue" );
    
    public static final ObjectProperty hasType = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasType" );
    
    public static final ObjectProperty hasInterface = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasInterface" );
    
    public static final ObjectProperty invokesMethod = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#invokesMethod" );
    
    public static final ObjectProperty hasClass = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasClass" );
    
    public static final ObjectProperty hasSourceFile = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasSourceFile" );
    
    public static final ObjectProperty extendsClass = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#extendsClass" );
    
    public static final ObjectProperty usesInterface = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#usesInterface" );
    
    public static final ObjectProperty hasAttribute = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasAttribute" );
    
    public static final ObjectProperty implements_ = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#implements" );
    
    public static final ObjectProperty usesClass = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#usesClass" );
    
    public static final ObjectProperty hasInternalClass = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasInternalClass" );
    
    public static final ObjectProperty hasMethod = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasMethod" );
    
    public static final ObjectProperty hasPackage = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasPackage" );
    
    public static final ObjectProperty hasInternalInterface = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasInternalInterface" );
    
    public static final ObjectProperty hasSubpackage = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#hasSubpackage" );
    
    public static final ObjectProperty programmingLanguage = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#programmingLanguage" );
    
    public static final ObjectProperty uses = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#uses" );
    
    public static final DatatypeProperty comment = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#comment" );
    
    public static final DatatypeProperty paramComment = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#paramComment" );
    
    public static final DatatypeProperty exceptionComment = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#exceptionComment" );
    
    public static final DatatypeProperty url = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#url" );
    
    public static final DatatypeProperty version = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#version" );
    
    public static final DatatypeProperty name = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#name" );
    
    public static final DatatypeProperty author = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#author" );
    
    public static final DatatypeProperty filename = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#filename" );
    
    public static final DatatypeProperty returnComment = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_source_code#returnComment" );
    
    public static final OntClass SourceCodeModule = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#SourceCodeModule" );
    
    public static final OntClass Interface = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Interface" );
    
    public static final OntClass Axiom_1 = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Axiom_1" );
    
    public static final OntClass Constructor = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Constructor" );
    
    public static final OntClass Class = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Class" );
    
    public static final OntClass Element = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Element" );
    
    public static final OntClass SourceCodeFile = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#SourceCodeFile" );
    
    public static final OntClass Method = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Method" );
    
    public static final OntClass ProgrammingLanguage = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#ProgrammingLanguage" );
    
    public static final OntClass Package = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Package" );
    
    public static final OntClass Attribute = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Attribute" );
    
    public static final OntClass SimpleType = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_source_code#SimpleType" );
    
    public static final Individual string = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#string", SimpleType );
    
    public static final Individual int_ = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#int", SimpleType );
    
    public static final Individual HTML = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#HTML", ProgrammingLanguage );
    
    public static final Individual char_ = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#char", SimpleType );
    
    public static final Individual boolean_ = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#boolean", SimpleType );
    
    public static final Individual byte_ = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#byte", SimpleType );
    
    public static final Individual Java = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Java", ProgrammingLanguage );
    
    public static final Individual Javascript = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Javascript", ProgrammingLanguage );
    
    public static final Individual Perl = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Perl", ProgrammingLanguage );
    
    public static final Individual XHTML = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#XHTML", ProgrammingLanguage );
    
    public static final Individual double_ = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#double", SimpleType );
    
    public static final Individual VisualBasic = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#VisualBasic", ProgrammingLanguage );
    
    public static final Individual Cplusplus = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Cplusplus", ProgrammingLanguage );
    
    public static final Individual PHP = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#PHP", ProgrammingLanguage );
    
    public static final Individual Ruby = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#Ruby", ProgrammingLanguage );
    
    public static final Individual CSharp = m_model.createIndividual( "http://www.qualipso.org/ontology/doc/qualipso_source_code#CSharp", ProgrammingLanguage );
    
}
