/* CVS $Id: $ */
package org.qualipso.advdoc.coreapi.ontology; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from ontologyqualipso_documentation.owl 
 * @author Auto-generated by schemagen on 11 abr 2008 14:28 
 */
public class QualiPSoDOC {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.qualipso.org/ontology/doc/qualipso_documentation#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasSubsection = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasSubsection" );
    
    public static final ObjectProperty hasAttribute = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasAttribute" );
    
    public static final ObjectProperty hasElement = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasElement" );
    
    public static final ObjectProperty hasText = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasText" );
    
    public static final ObjectProperty hasComment = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasComment" );
    
    public static final ObjectProperty hasDocument = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasDocument" );
    
    public static final ObjectProperty hasSubfolder = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasSubfolder" );
    
    public static final ObjectProperty publisher = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#publisher" );
    
    public static final ObjectProperty referencesTo = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#referencesTo" );
    
    public static final ObjectProperty creator = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#creator" );
    
    public static final ObjectProperty contributor = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#contributor" );
    
    public static final ObjectProperty hasFolder = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#hasFolder" );
    
    public static final DatatypeProperty title = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#title" );
    
    public static final DatatypeProperty level = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#level" );
    
    public static final DatatypeProperty dateAccepted = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#dateAccepted" );
    
    public static final DatatypeProperty modified = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#modified" );
    
    public static final DatatypeProperty dateSubmitted = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#dateSubmitted" );
    
    public static final DatatypeProperty attributeValue = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#attributeValue" );
    
    public static final DatatypeProperty license = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#license" );
    
    public static final DatatypeProperty sectionNumber = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#sectionNumber" );
    
    public static final DatatypeProperty subject = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#subject" );
    
    public static final DatatypeProperty abstract_ = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#abstract" );
    
    public static final DatatypeProperty description = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#description" );
    
    public static final DatatypeProperty language = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#language" );
    
    public static final DatatypeProperty textContents = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#textContents" );
    
    public static final DatatypeProperty attributeName = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_documentation#attributeName" );
    
    public static final OntClass Document = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Document" );
    
    public static final OntClass Attribute = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Attribute" );
    
    public static final OntClass Comment = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Comment" );
    
    public static final OntClass Entity = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Entity" );
    
    public static final OntClass Table = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Table" );
    
    public static final OntClass TextDocument = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#TextDocument" );
    
    public static final OntClass Text = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Text" );
    
    public static final OntClass Figure = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Figure" );
    
    public static final OntClass Section = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Section" );
    
    public static final OntClass DocumentStorage = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#DocumentStorage" );
    
    public static final OntClass Reference = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Reference" );
    
    public static final OntClass Abstract = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Abstract" );
    
    public static final OntClass Folder = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Folder" );
    
    public static final OntClass List = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#List" );
    
    public static final OntClass Paragraph = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#Paragraph" );
    
    public static final OntClass DocElement = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_documentation#DocElement" );
    
}
