/* CVS $Id: $ */
package org.qualipso.advdoc.coreapi.ontology; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from ontologyqualipso_mailinglist.owl 
 * @author Auto-generated by schemagen on 11 abr 2008 14:28 
 */
public class QualiPSoML {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A user which e-mail messages can be delivered</p> */
    public static final ObjectProperty cc = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#cc" );
    
    /** <p>A user which e-mail messages can be delivered</p> */
    public static final ObjectProperty to = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#to" );
    
    /** <p>The user that created the mail</p> */
    public static final ObjectProperty from = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#from" );
    
    /** <p>The user fullname</p> */
    public static final DatatypeProperty cc_fullname = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#cc_fullname" );
    
    /** <p>An e-mail address identifying a location to which e-mail messages can be delivered</p> */
    public static final DatatypeProperty cc_address = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#cc_address" );
    
    /** <p>The user fullname</p> */
    public static final DatatypeProperty to_fullname = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#to_fullname" );
    
    /** <p>An e-mail address identifying a location to which e-mail messages can be delivered</p> */
    public static final DatatypeProperty to_address = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#to_address" );
    
    /** <p>The user fullname</p> */
    public static final DatatypeProperty from_fullname = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#from_fullname" );
    
    /** <p>The email of the user that created the mail</p> */
    public static final DatatypeProperty from_address = m_model.createDatatypeProperty( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#from_address" );
    
    /** <p>An electronic mail.</p> */
    public static final OntClass Mail = m_model.createClass( "http://www.qualipso.org/ontology/doc/qualipso_maillinglist#Mail" );
    
}
