/* CVS $Id: $ */
package org.qualipso.advdoc.coreapi.ontology; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from ontologyqualipso_relationship.owl 
 * @author Auto-generated by schemagen on 11 abr 2008 14:28 
 */
public class QualiPSoRS {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.qualipso.org/ontology/doc/qualipso_relationship#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasAuthor = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#hasAuthor" );
    
    public static final ObjectProperty documentsSourceCode = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#documentsSourceCode" );
    
    public static final ObjectProperty bugAboutSourceCodeFile = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#bugAboutSourceCodeFile" );
    
    public static final ObjectProperty mailAboutRevision = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#mailAboutRevision" );
    
    public static final ObjectProperty bugAboutDocumentSection = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#bugAboutDocumentSection" );
    
    public static final ObjectProperty hasForum = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#hasForum" );
    
    public static final ObjectProperty relatedToDocument = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#relatedToDocument" );
    
    public static final ObjectProperty hasSourceCodeModule = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#hasSourceCodeModule" );
    
    public static final ObjectProperty mailAboutIssue = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#mailAboutIssue" );
    
    public static final ObjectProperty mailAboutDocument = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#mailAboutDocument" );
    
    public static final ObjectProperty bugAboutDocument = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#bugAboutDocument" );
    
    public static final ObjectProperty relatedToIssue = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#relatedToIssue" );
    
    public static final ObjectProperty hasIssue = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#hasIssue" );
    
    public static final ObjectProperty issueAboutRevision = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#issueAboutRevision" );
    
    public static final ObjectProperty bugAboutSourceCodeModule = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#bugAboutSourceCodeModule" );
    
    public static final ObjectProperty mailAboutSourceCode = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#mailAboutSourceCode" );
    
    public static final ObjectProperty postAboutRevision = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#postAboutRevision" );
    
    public static final ObjectProperty relatedToSourceCodeFile = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#relatedToSourceCodeFile" );
    
    public static final ObjectProperty hasDocStorage = m_model.createObjectProperty( "http://www.qualipso.org/ontology/doc/qualipso_relationship#hasDocStorage" );
    
}
