/* CVS $Id: $ */
package org.qualipso.advdoc.coreapi.ontology; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from ontologysioc.rdf 
 * @author Auto-generated by schemagen on 11 abr 2008 14:28 
 */
public class SIOC {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://rdfs.org/sioc/ns#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A User who is a member of this Usergroup.</p> */
    public static final ObjectProperty has_member = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_member" );
    
    /** <p>A topic of interest, linking to the appropriate URI, e.g., in the Open Directory 
     *  Project or of a SKOS category.</p>
     */
    public static final ObjectProperty topic = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#topic" );
    
    /** <p>A data Space which this resource is a part of.</p> */
    public static final ObjectProperty has_space = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_space" );
    
    /** <p>A User who is a moderator of this Forum.</p> */
    public static final ObjectProperty has_moderator = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_moderator" );
    
    /** <p>A Role that this User has.</p> */
    public static final ObjectProperty has_function = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_function" );
    
    /** <p>A Container that a User is subscribed to.</p> */
    public static final ObjectProperty subscriber_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#subscriber_of" );
    
    /** <p>A User that this Container is owned by.</p> */
    public static final ObjectProperty has_owner = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_owner" );
    
    /** <p>The Container to which this Item belongs.</p> */
    public static final ObjectProperty has_container = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_container" );
    
    /** <p>Refers to the foaf:Agent or foaf:Person who owns this sioc:User online account.</p> */
    public static final ObjectProperty account_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#account_of" );
    
    /** <p>A feed (e.g., RSS, Atom, etc.) pertaining to this resource (e.g., for a Forum, 
     *  Site, User, etc.).</p>
     */
    public static final ObjectProperty feed = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#feed" );
    
    /** <p>This is the User who made this Item.</p> */
    public static final ObjectProperty has_creator = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_creator" );
    
    /** <p>A Container owned by a particular User, for example, a weblog or image gallery.</p> */
    public static final ObjectProperty owner_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#owner_of" );
    
    /** <p>A resource which belongs to this data Space.</p> */
    public static final ObjectProperty space_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#space_of" );
    
    /** <p>The Site that hosts this Forum.</p> */
    public static final ObjectProperty has_host = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_host" );
    
    /** <p>An image or depiction used to represent this User.</p> */
    public static final ObjectProperty avatar = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#avatar" );
    
    /** <p>Links extracted from hyperlinks within a SIOC concept, e.g., Post or Site.</p> */
    public static final ObjectProperty links_to = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#links_to" );
    
    /** <p>Previous Item or Post in a given Container sorted by date.</p> */
    public static final ObjectProperty previous_by_date = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#previous_by_date" );
    
    /** <p>A User who has this Role.</p> */
    public static final ObjectProperty function_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#function_of" );
    
    /** <p>An resource that is a part of this subject.</p> */
    public static final ObjectProperty has_part = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_part" );
    
    /** <p>Links to an Item or Post which this Item or Post is a reply to.</p> */
    public static final ObjectProperty reply_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#reply_of" );
    
    /** <p>A resource that the subject is a part of.</p> */
    public static final ObjectProperty part_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#part_of" );
    
    /** <p>A User who modified this Item.</p> */
    public static final ObjectProperty has_modifier = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_modifier" );
    
    /** <p>Related Posts for this Post, perhaps determined implicitly from topics or 
     *  references.</p>
     */
    public static final ObjectProperty related_to = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#related_to" );
    
    /** <p>Points to a Usergroup that has certain access to this Space.</p> */
    public static final ObjectProperty has_usergroup = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_usergroup" );
    
    /** <p>Next Item or Post in a given Container sorted by date.</p> */
    public static final ObjectProperty next_by_date = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#next_by_date" );
    
    /** <p>A child Container or Forum that this Container or Forum is a parent of.</p> */
    public static final ObjectProperty parent_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#parent_of" );
    
    /** <p>A User who is an administrator of this Site.</p> */
    public static final ObjectProperty has_administrator = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_administrator" );
    
    /** <p>A Forum that User is a moderator of.</p> */
    public static final ObjectProperty moderator_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#moderator_of" );
    
    /** <p>Links to the next revision of this Item or Post.</p> */
    public static final ObjectProperty next_version = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#next_version" );
    
    /** <p>A Role that has a scope of this Forum.</p> */
    public static final ObjectProperty scope_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#scope_of" );
    
    /** <p>A Space that the Usergroup has access to.</p> */
    public static final ObjectProperty usergroup_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#usergroup_of" );
    
    /** <p>An Item that the User is a creator of.</p> */
    public static final ObjectProperty creator_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#creator_of" );
    
    /** <p>A URI of a document which contains this SIOC object.</p> */
    public static final ObjectProperty link = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#link" );
    
    /** <p>Links either created explicitly or extracted implicitly on the HTML level 
     *  from the Post.</p>
     */
    public static final ObjectProperty reference = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#reference" );
    
    /** <p>A Forum that this Role applies to.</p> */
    public static final ObjectProperty has_scope = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_scope" );
    
    /** <p>An Item that this Container contains.</p> */
    public static final ObjectProperty container_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#container_of" );
    
    /** <p>A User who is subscribed to this Container.</p> */
    public static final ObjectProperty has_subscriber = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_subscriber" );
    
    /** <p>A Post may have a sibling or a twin that exists in a different Forum, but 
     *  the siblings may differ in some small way (for example, language, category, 
     *  etc.). The sibling of this Post should be self-describing (that is, it should 
     *  contain all available information).</p>
     */
    public static final ObjectProperty sibling = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#sibling" );
    
    /** <p>A Container or Forum that this Container or Forum is a child of.</p> */
    public static final ObjectProperty has_parent = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_parent" );
    
    /** <p>An Item that this User has modified.</p> */
    public static final ObjectProperty modifier_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#modifier_of" );
    
    /** <p>Points to an Item or Post that is a reply or response to this Item or Post.</p> */
    public static final ObjectProperty has_reply = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#has_reply" );
    
    /** <p>Links to a previous revision of this Item or Post.</p> */
    public static final ObjectProperty previous_version = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#previous_version" );
    
    /** <p>Specifies that this Item is about a particular resource, e.g., a Post describing 
     *  a book, hotel, etc.</p>
     */
    public static final ObjectProperty about = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#about" );
    
    /** <p>An electronic mail address of the User.</p> */
    public static final ObjectProperty email = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#email" );
    
    /** <p>A Site that the User is an administrator of.</p> */
    public static final ObjectProperty administrator_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#administrator_of" );
    
    /** <p>A Usergroup that this User is a member of.</p> */
    public static final ObjectProperty member_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#member_of" );
    
    /** <p>The URI of a file attached to a Post.</p> */
    public static final ObjectProperty attachment = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#attachment" );
    
    /** <p>A Forum that is hosted on this Site.</p> */
    public static final ObjectProperty host_of = m_model.createObjectProperty( "http://rdfs.org/sioc/ns#host_of" );
    
    /** <p>When this was modified, in ISO 8601 format.</p> */
    public static final DatatypeProperty modified_at = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#modified_at" );
    
    /** <p>The encoded content of the Post, contained in CDATA areas.</p> */
    public static final DatatypeProperty content_encoded = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#content_encoded" );
    
    /** <p>When this was created, in ISO 8601 format.</p> */
    public static final DatatypeProperty created_at = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#created_at" );
    
    /** <p>The number of replies that this Post has. Useful for when the reply structure 
     *  is absent.</p>
     */
    public static final DatatypeProperty num_replies = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#num_replies" );
    
    /** <p>Keyword(s) describing subject of the Post.</p> */
    public static final DatatypeProperty subject = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#subject" );
    
    /** <p>An identifier of a SIOC concept instance. For example, a user ID. Must be 
     *  unique for instances of each type of SIOC concept within the same site.</p>
     */
    public static final DatatypeProperty id = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#id" );
    
    /** <p>The number of times this Item, Thread, User profile, etc. has been viewed.</p> */
    public static final DatatypeProperty num_views = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#num_views" );
    
    /** <p>First (real) name of this User. Synonyms include given name or christian name.</p> */
    public static final DatatypeProperty first_name = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#first_name" );
    
    /** <p>Last (real) name of this user. Synonyms include surname or family name.</p> */
    public static final DatatypeProperty last_name = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#last_name" );
    
    /** <p>An electronic mail address of the User, encoded using SHA1.</p> */
    public static final DatatypeProperty email_sha1 = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#email_sha1" );
    
    /** <p>The content of the Post in plain text format.</p> */
    public static final DatatypeProperty content = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#content" );
    
    /** <p>The content of the Post.</p> */
    public static final DatatypeProperty description = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#description" );
    
    /** <p>The IP address used when creating this Item. This can be associated with a 
     *  creator. Some wiki articles list the IP addresses for the creator or modifiers 
     *  when the usernames are absent.</p>
     */
    public static final DatatypeProperty ip_address = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#ip_address" );
    
    /** <p>The name of a SIOC instance, e.g. a username for a User, group name for a 
     *  Usergroup, etc.</p>
     */
    public static final DatatypeProperty name = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#name" );
    
    /** <p>A note associated with this Post, for example, if it has been edited by a 
     *  User.</p>
     */
    public static final DatatypeProperty note = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#note" );
    
    /** <p>This is the title (subject line) of the Post. Note that for a Post within 
     *  a threaded discussion that has no parents, it would detail the topic thread.</p>
     */
    public static final DatatypeProperty title = m_model.createDatatypeProperty( "http://rdfs.org/sioc/ns#title" );
    
    /** <p>A discussion area on which Posts or entries are made.</p> */
    public static final OntClass Forum = m_model.createClass( "http://rdfs.org/sioc/ns#Forum" );
    
    /** <p>A container for a series of threaded discussion Posts or Items.</p> */
    public static final OntClass Thread = m_model.createClass( "http://rdfs.org/sioc/ns#Thread" );
    
    /** <p>An article or message that can be posted to a Forum.</p> */
    public static final OntClass Post = m_model.createClass( "http://rdfs.org/sioc/ns#Post" );
    
    /** <p>A User account in an online community site.</p> */
    public static final OntClass User = m_model.createClass( "http://rdfs.org/sioc/ns#User" );
    
    /** <p>A Role is a function of a User within a scope of a particular Forum, Site, 
     *  etc.</p>
     */
    public static final OntClass Role = m_model.createClass( "http://rdfs.org/sioc/ns#Role" );
    
    /** <p>A set of User accounts whose owners have a common purpose or interest. Can 
     *  be used for access control purposes.</p>
     */
    public static final OntClass Usergroup = m_model.createClass( "http://rdfs.org/sioc/ns#Usergroup" );
    
    /** <p>A Site can be the location of an online community or set of communities, with 
     *  Users and Usergroups creating Items in a set of Containers. It can be thought 
     *  of as a web-accessible data Space.</p>
     */
    public static final OntClass Site = m_model.createClass( "http://rdfs.org/sioc/ns#Site" );
    
    /** <p>An area in which content Items are contained.</p> */
    public static final OntClass Container = m_model.createClass( "http://rdfs.org/sioc/ns#Container" );
    
    /** <p>Community is a high-level concept that defines an online community and what 
     *  it consists of.</p>
     */
    public static final OntClass Community = m_model.createClass( "http://rdfs.org/sioc/ns#Community" );
    
    /** <p>A content Item that can be posted to or created within a Container.</p> */
    public static final OntClass Item = m_model.createClass( "http://rdfs.org/sioc/ns#Item" );
    
    /** <p>A Space is a place where data resides, e.g., on a website, desktop, fileshare, 
     *  etc.</p>
     */
    public static final OntClass Space = m_model.createClass( "http://rdfs.org/sioc/ns#Space" );
    
}
